name: CommandHelper
main: com.laytonsmith.commandhelper.CommandHelperPlugin
version: "${project.version}"
softdepend: [Vault]
commands:
    repeat:
        description: Repeat the last command
        usage: /<command>
        aliases: .
    alias:
        description: Create an alias
        usage: /<command> <alias>
    delalias:
        description: Remove an alias
        usage: /<command> <name>
    reloadaliases:
        description: Reloads aliases
        usage: /<command>
        aliases: [reloadalias, recompile]
    viewalias:
        description: View all user defined aliases
        usage: /<command>
        aliases: viewaliases
    interpreter:
        description: Puts your chat into interpreter mode
        usage: /<command>
    commandhelper:
        description: Used to gain meta information about CommandHelper
        usage: /<command> <arguments>
    runalias:
        description: If another plugin wants to run a CommandHelper command, it isn't always straightforward to do that, because of the way bukkit works. To get around this, you may use this command. "/runalias /command to run" will fire off the alias "/command to run"
        usage: /<command> <otherCommand>
    interpreter-on:
        description: Turns on the interpreter for however long is specified in the preferences option "interpreter-timeout". This only does something if run from console.
        usage: /<command>